---
- name: Monitoring Automation Controller with Prometheus + Grafana
  hosts: localhost
  # collections:
  #   - kubernetes.core
  #   - community.general
  pre_tasks:
  - name: Install needed python package
    ansible.builtin.pip:
      name: 
      - kubernetes
      - jmespath

  - name: Create the aap namespace
    kubernetes.core.k8s:
      state: present
      template: 01-aap-project.yml.j2

  - name: Deploy AAP
    kubernetes.core.k8s:
      state: present
      template: 02-aap-sub.yml.j2

  roles:
    - aap_prometheus_grafana
